name = "apihero-proxy"
main = "dist/index.mjs"
compatibility_date = "2022-09-30"
routes = [
	{ pattern = "proxy.apihero.run", custom_domain = true, zone_name = "apihero.run" }
]

[build]
command = "node build.js"

[vars]
LOGS_URL = "https://logs.apihero.run"

[env.local.vars]
LOGS_URL = "http://localhost:3001"
LOGS_DEBUG = true

[miniflare]
kv_persist = true
cache_persist = true

# Required secrets to be set:
# - LOGS_AUTHENTICATION_TOKEN